  version: "3.9"

  services:
    redis:
      image: redis:7
      container_name: myredis
      ports:
        - "6379:6379"

    upload-service:
      build: ./upload-service
      ports:
        - "3011:3000"
      depends_on:
        - redis
      env_file:
        - ./.env

    deployment-service:
      build: ./deploy-service
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./shared-output:/app/dist/output
      environment:
        - HOST_SHARED_OUTPUT=${PWD}/shared-output
      depends_on:
        - redis
        - upload-service
      env_file:
        - ./.env

    request-handler-service:
      build: ./request-handler
      ports:
        - "3012:3001"
      depends_on:
        - redis
      env_file:
        - ./.env
    
    frontend:
      build: ./frontend
      ports:
        - "3014:3000"
      depends_on:
        - upload-service
        - deployment-service
        - request-handler-service
        - websocket-backend
      env_file:
        - ./frontend/.env

    websocket-backend:
      build: ./ws-server
      ports:
        - "8081:8080"
      depends_on:
        - upload-service
        - deployment-service
        - redis
      env_file:
        - ./.env